### ISSUE TITLE
get-component-node-list does fails without printing anything useful

### ISSUE THREAD

**Issue by tpdownes** [UnivaCorporation/tortuga#607]
On an otherwise running installation of Tortuga 7.1.0, the command `get-component-node-list` fails without reporting anything useful.
```
[root@ip-10-0-200-113 ~]# get-component-node-list
'SoftwareProfile' object has no attribute 'components'
```

**Comment by tprestegard** [comment]
I fixed a bunch of similar issues (see b01da78ab2c95de9a478a7dc83752c1ee703736d), but after all that, I found that running `SoftwareProfile.getNodes()` just returns an empty list even if the software profile definitely has nodes.  I did a bit of digging and tried adding a line like `'nodes': True` [here](https://github.com/UnivaCorporation/tortuga/blob/master/src/installer/src/tortuga/db/softwareProfileDbApi.py#L160), but it didn't seem to have any effect.  @dtougas, do you have any insights into how to fix that?  Otherwise I'll dig a bit further maybe once the current sprint is done.

**Comment by tpdownes** [comment]
It would at least be useful for it to print out what the command is supposed to do. List all nodes with a given component?

**Comment by tprestegard** [comment]
Yeah, from looking at the code, it will print a list of nodes with that component enabled for each software profile... I agree that a help dialog would be useful.
